### ISSUE TITLE
remove redundant return values that exist for OO-style fluent programming

### ISSUE THREAD

**Issue by bbarker** [purescript-web/purescript-web-dom#11]
I recently opened an [SO question](https://stackoverflow.com/questions/56876573/why-does-node-appendchild-seemingly-always-return-its-input-value?noredirect=1#comment100302003_56876573) to understand this in the case of [appendChild](https://pursuit.purescript.org/packages/purescript-web-dom/3.0.0/docs/Web.DOM.Node#v:appendChild); it really seems like this should be modeled as returning `Effect[Unit]` (otherwise it is bit confusing and one has to use `discard` in some form). There may be other methods like this, but so far, this is the only one I've come across while writing my own code.

**Comment by garyb** [comment]
Sounds reasonable. I'll try to remember the suggestion next time there's a need to break some stuff!

**Comment by hdgarrood** [comment]
I don't think 0.14 will necessarily require breaking any of the purescript-web packages, but it does break a few libraries which are quite low down in the ecosystem, so perhaps this might be a good time to do this?

**Comment by thomashoneyman** [comment]
We're about to update this library for the upcoming 0.14 release. I think this deserves to be a part of those changes.
