### ISSUE TITLE
No Element -> DOMTokenList

### ISSUE THREAD

**Issue by alextes** [purescript-web/purescript-web-dom#15]
There's a `HTMLElement -> Effect DOMTokenList` in `web-html` but that's a big dep when wanting to work on classes and it seems getting a DOMTokenList is valid for any [element](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) and Element is in `web-dom`. Any reason why `classList` is in `web-html`. Could we have it in both? Should the one in `web-html` be in `web-dom`?

The implementation of `classList` is a simple method call.

Just trying to understand the why of it mostly.

**Comment by alextes** [comment]
I'll ask in Slack first come to think of it.

**Comment by garyb** [comment]
There's no `classList` in here as this library is for the DOM API, `-web-html` is for the HTML API, which is where `classList` is defined :wink:

**Comment by garyb** [comment]
Actually, my mistake, `classList` is defined for both `Element` and `HTMLElement` interfaces, so yeah it could be added here.

**Comment by alextes** [comment]
I'll make the PR! 🙌
