### ISSUE TITLE
Unclear how to get a Document

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [purescript-web/purescript-web-dom#19]
there seems no way to get the root document

**Comment by garyb** [comment]
It's part of the HTML API rather than the more general DOM API: https://pursuit.purescript.org/packages/purescript-web-html/2.3.0/docs/Web.HTML.Window#v:document

**Comment by BebeSparkelSparkel** [comment]
That seems to be a pretty far leap especially since *web-dom* uses the type `Document` and *web-html* uses type `HTMLDocument`

**Comment by BebeSparkelSparkel** [comment]
And there is no documentation in `Web.DOM.Document` stating that

**Comment by garyb** [comment]
Blame the W3C :smile:

`Document` is only part of the interface that the `window.document` gives you, `HTMLDocument` is the rest.

Documenting it in `Web.DOM.Document` would be a bit like documenting RSS in an XML library: it's talking about specifics for something that is more general.

**Comment by BebeSparkelSparkel** [comment]
I would say if the "XML" library had a common use case that a large proportion of the libraries user base was using for "RSS" then it would be worth noting in the docs to save a bit of frustration.

**Comment by garyb** [comment]
Yeah you're right, that is kinda a silly argument. I think the only other use cases for `Document` in the browser are for XML (and SVG by extension), but almost everybody is using it in the HTML context.

**Comment by BebeSparkelSparkel** [comment]
Thanks
