### ISSUE TITLE
querySelector and ParentNode

### ISSUE THREAD

**Issue by maddie927** [purescript-web/purescript-web-dom#2]
Am I missing something or is `unsafeCoerce` the only way to get your hands on a [ParentNode](https://pursuit.purescript.org/packages/purescript-web-dom/1.0.0/docs/Web.DOM.ParentNode#t:ParentNode)? [parentNode](https://pursuit.purescript.org/packages/purescript-web-dom/1.0.0/docs/Web.DOM.Node#v:parentNode) is the only sort-of related function, and it returns a `Node`.

Should `querySelector` just take an `Element`? `querySelector` itself already returns a `Maybe` to handle failure and the JS `querySelector` function is a method on [Element](https://developer.mozilla.org/en-US/docs/Web/API/element/querySelector).

**Comment by garyb** [comment]
You can turn any `Document`, `DocumentFragment`, or `Element` into a `ParentNode` with the corresponding `toParentNode` functions.

As for the type of querySelector, we just do what the spec say :smile: - https://www.w3.org/TR/dom/#interface-parentnode (that's also where you can see that the other types that implement it).

**Comment by maddie927** [comment]
Oh.. why don't those show up when searching for "ParentNode" on pursuit? Thanks!

**Comment by garyb** [comment]
Argh, that's really unfortunate 😞 I guess it only finds based on prefixes, since `toPare` and the like seem to have results for it.

**Comment by garyb** [comment]
For future reference (although you know this now I'm sure!) - there are `toX` functions for any upcasts that the spec says are possible, and there are `fromX` for downcasts (so these return `Maybe` as they might fail).

**Comment by maddie927** [comment]
Makes sense, thanks!
