### ISSUE TITLE
hasAttribute in Web.DOM.Element fails

### ISSUE THREAD

**Issue by ghost** [purescript-web/purescript-web-dom#22]
The cause is that the return type has not an effectful implementation.

Instead of ...
exports.hasAttribute = function(name) {
  return function (element) {
    return element.hasAttribute(name);
  };
};

... the implementation should be ...
exports.hasAttribute = function(name) {
  return function (element) {
    return function () {   
      return element.hasAttribute(name);
    };
  };
};

**Comment by garyb** [comment]
Thanks for the report!
