### ISSUE TITLE
Argument ordering for better composition

### ISSUE THREAD

**Issue by eslamahmed148** [purescript-web/purescript-web-dom#42]
In the source code, the `document` object is injected as the last argument for the functions that have a dependency on it.

Isn't it better, in general, if dependencies are injected first?

Example:

```js
// Current behavior:
const Header = createElement('header')(document);

// What I was looking for:
const createElementUsingBrowserDocument = createElement(document);
const Header = createElementUsingBrowserDocument('header');
```

This is similar to DI patterns used in functional programming.

For instance, if I want to compose a function for creating users using a dependency-injected database provider:

```js
const makeModelCreator = database => model => entity => (
  database.table(model).create(entity)
);

const useLocalStorageModelCreator = makeModelCreator(implementation);
const useFirebaseModelCreator = makeModelCreator(implementation);

const createUser = useLocalStorageModelCreator('users');
// or
const createUser = useFirebaseModelCreator('users');

createUser({ name: 'Mike' }).then();
```

In this example, the `database` is equivalent to the `document` object. It is the *dependency* that is handling the function.

Also, maybe this doesn't matter in our context (Web DOM), as the `document` is not an interface that can be swapped with multiple implementations as a database provider. But, I don't know.

I'd love to hear your thoughts on this.

Thank you.

**Comment by garyb** [comment]
Hey! Sorry this never got replied to.

The current argument order is intended for convenient composition, just not in the way you're looking at it - it's so this kind of pattern is convenient:

``` purescript
scrollToTop = do
  body ← Document.documentElement <<< HTMLDocument.toDocument =<< Window.document =<< HTML.window
  traverse_ (Element.setScrollTop 0.0) body
```
