### ISSUE TITLE
Any interest in adding ResizeObserver?

### ISSUE THREAD

**Issue by nsaunders** [purescript-web/purescript-web-dom#45]
Please let me know, and I'd be happy to contribute if so... Thanks in advance for your response!

**Comment by garyb** [comment]
It looks like `ResizeObserver` [has its own spec](https://drafts.csswg.org/resize-observer), so we'd want to make a separate library for that, but, sure! 🙂

**Comment by nsaunders** [comment]
Thanks, @garyb, I've done it! https://github.com/nsaunders/purescript-web-resize-observer

Would you please let me know if there would be any interest in transferring this to the purescript-web organization?
