### ISSUE TITLE
Probably clientX, scrollX should return Int

### ISSUE THREAD

**Issue by wclr** [purescript-web/purescript-web-dom#50]
This is just in case it is desirable to keep API more strict.

For props like `clientHeight`, `scroll height`, etc there is a notice:

> This property will round the value to an integer. If you need a fractional value, use [element.getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect).

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight

**Comment by garyb** [comment]
In the CSSOM View Module spec `clientX` and `scrollX` are defined as `double` so those should definitely be `Number`, and `clientHeight` and `scrollHeight` are defined as `long`... `long` is too big for `Int`, so, `Number`. 🙂

**Comment by wclr** [comment]
Ah, yes, so `Number`.
