### ISSUE TITLE
Is `HTMLCollection` API implemented?

### ISSUE THREAD

**Issue by paluh** [purescript-web/purescript-web-dom#8]
I'm not sure how to fold over `HTMLCollection`. Is this [API](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection) somewhere implemented in `purescript-web`?

**Comment by garyb** [comment]
Indeed! https://pursuit.purescript.org/packages/purescript-web-dom/2.0.0/docs/Web.DOM.HTMLCollection

**Comment by paluh** [comment]
Sorry for spam and Thanks a lot!
