### ISSUE TITLE
nodeValue should return Effect (Maybe String)

### ISSUE THREAD

**Issue by bbarker** [purescript-web/purescript-web-dom#9]
Even based on the [doc string](https://pursuit.purescript.org/packages/purescript-web-dom/2.0.0/docs/Web.DOM.Node#v:nodeValue), it seems this should be the case, and it is easy enough to come up with examples where you get `null`. Like if you run this in chromium:

```javascript
xmlText = "<foo>foobar<bar></foo>";
parser = new DOMParser();
doc = parser.parseFromString(xmlText, 'application/xml');
var tst = doc.getElementsByTagNameNS("http://www.w3.org/1999/xhtml", "parsererror").item(0).childNodes[0].nodeValue; 
console.log(tst)
```

**Comment by garyb** [comment]
😬 yeah, there definitely should be a `Maybe` in there.

**Comment by bbarker** [comment]
FYI, and maybe this is planned, it seems like v3.0 isn't up on pursuit - but is on bower.

**Comment by garyb** [comment]
Thanks, it's pushed now. It failed to auto publish with the release due to an outdated pulp dependency I think.
